### ISSUE TITLE
v2.0.32 not working for me

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1050]

**Comment by ghost** [comment]
<details>
  <summary># systemctl status dnscrypt-proxy</summary>

```
● dnscrypt-proxy.service - DNSCrypt-proxy
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-11-18 00:00:36 UTC; 4min 44s ago
     Docs: https://github.com/jedisct1/dnscrypt-proxy/wiki
 Main PID: 1563 (dnscrypt-proxy)
       IP: 5.9K in, 1.8K out
    Tasks: 12 (limit: 14)
   Memory: 5.9M (high: 16.0M max: 20.0M)
   CGroup: /system.slice/dnscrypt-proxy.service
           └─1563 /usr/local/bin/dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml

Nov 18 00:00:36 host systemd[1]: Started DNSCrypt-proxy.
```

</details>


<details>
  <summary># journalctl -u dnscrypt-proxy</summary>

```
Nov 18 00:00:36 host dnscrypt-proxy[1538]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 18 00:00:36 host dnscrypt-proxy[1538]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x3bff84]
Nov 18 00:00:36 host dnscrypt-proxy[1538]: goroutine 12 [running]:
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*BlockedNames).check(0x0, 0x191e000, 0x1ab8120, 0x15, 0x80a3c0, 0x16)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:104 +0x18
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*PluginBlockName).Eval(0x18f3820, 0x191e000, 0x1a220a0, 0x0, 0x0)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:100 +0xd0
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*PluginsState).ApplyQueryPlugins(0x191e000, 0x1898a98, 0x188a000, 0x27, 0xfff, 0x1900011, 0xa, 0x0, 0x0, 0x0, ...)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/plugins.go:251 +0x190
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*Proxy).processIncomingQuery(0x1898900, 0x19040a0, 0x48e60d, 0x3, 0x48e604, 0x3, 0x188a000, 0x27, 0xfff, 0x1a6d070, ...)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/proxy.go:367 +0x150
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*Proxy).udpListener.func1(0x1898900, 0x188a000, 0x27, 0xfff, 0x1a6d070, 0x18f3c30)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/proxy.go:219 +0xe4
Nov 18 00:00:36 host dnscrypt-proxy[1538]: created by main.(*Proxy).udpListener
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/proxy.go:212 +0x7c
Nov 18 00:00:36 host dnscrypt-proxy[1538]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 18 00:00:36 host dnscrypt-proxy[1538]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x3bff84]
Nov 18 00:00:36 host dnscrypt-proxy[1538]: goroutine 11 [running]:
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*BlockedNames).check(0x0, 0x189c200, 0x1a68000, 0x15, 0x80a3c0, 0x16)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:104 +0x18
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*PluginBlockName).Eval(0x18f3820, 0x189c200, 0x1816050, 0x0, 0x0)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:100 +0xd0
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*PluginsState).ApplyQueryPlugins(0x189c200, 0x1898a98, 0x1946000, 0x27, 0xfff, 0x1900011, 0xa, 0x0, 0x0, 0x0, ...)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/plugins.go:251 +0x190
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*Proxy).processIncomingQuery(0x1898900, 0x19040a0, 0x48e60d, 0x3, 0x48e604, 0x3, 0x1946000, 0x27, 0xfff, 0x1948000, ...)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/proxy.go:367 +0x150
Nov 18 00:00:36 host dnscrypt-proxy[1538]: main.(*Proxy).udpListener.func1(0x1898900, 0x1946000, 0x27, 0xfff, 0x1948000, 0x18f3c30)
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/proxy.go:219 +0xe4
Nov 18 00:00:36 host dnscrypt-proxy[1538]: created by main.(*Proxy).udpListener
Nov 18 00:00:36 host dnscrypt-proxy[1538]:         /tmp/tmp.5GhuziVlNP/dnscrypt-proxy/dnscrypt-proxy/proxy.go:212 +0x7c
Nov 18 00:00:36 host systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 18 00:00:36 host systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
Nov 18 00:00:36 host systemd[1]: dnscrypt-proxy.service: Received 5.9K IP traffic, sent 1.9K IP traffic.
Nov 18 00:00:36 host systemd[1]: dnscrypt-proxy.service: Service RestartSec=100ms expired, scheduling restart.
Nov 18 00:00:36 host systemd[1]: dnscrypt-proxy.service: Scheduled restart job, restart counter is at 5.
Nov 18 00:00:36 host systemd[1]: Stopped DNSCrypt-proxy.
Nov 18 00:00:36 host systemd[1]: dnscrypt-proxy.service: Received 5.9K IP traffic, sent 1.9K IP traffic.
Nov 18 00:00:36 host systemd[1]: Started DNSCrypt-proxy.
```

</details>

<details>
  <summary># cat .../dnscrypt-proxy.log</summary>

```
[2019-11-18 00:00:37] [NOTICE] dnscrypt-proxy 2.0.32
[2019-11-18 00:00:37] [NOTICE] Loading the set of whitelisting rules from [whitelist.txt]
[2019-11-18 00:00:37] [NOTICE] Firefox workaround initialized
[2019-11-18 00:00:37] [NOTICE] Loading the set of blocking rules from [blacklist.txt]
[2019-11-18 00:00:37] [NOTICE] Loading the set of cloaking rules from [cloaking-rules.txt]
[2019-11-18 00:00:37] [NOTICE] Loading the set of forwarding rules from [forwarding-rules.txt]
[2019-11-18 00:00:37] [NOTICE] Now listening to 192.168.1.1:53 [UDP]
[2019-11-18 00:00:37] [NOTICE] Now listening to 192.168.1.1:53 [TCP]
[2019-11-18 00:00:39] [INFO] [cloudflare] TLS version: 304 - Protocol: h2 - Cipher suite: 4867
[2019-11-18 00:00:40] [NOTICE] [cloudflare] OK (DoH) - rtt: 48ms
[2019-11-18 00:00:40] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 48ms)
[2019-11-18 00:00:40] [NOTICE] dnscrypt-proxy is ready - live servers: 1
```

</details>

<details>
  <summary># dig @192.168.1.1 github.com</summary>

```
; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @192.168.1.1 github.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

</details

**Comment by ghost** [comment]
Thank you. It works now.

**Comment by sergeevabc** [comment]
Err… 2.0.32 crashes on Windows 7 x64 as follows
```
[NOTICE] dnscrypt-proxy 2.0.32
[NOTICE] Network connectivity detected
[NOTICE] Source [public-resolvers] loaded
[NOTICE] Loading the set of whitelisting rules from [whitelist.txt]
[NOTICE] Firefox workaround initialized
[NOTICE] Loading the set of blocking rules from [blacklist.txt]
[NOTICE] Now listening to 127.0.0.1:53 [UDP]
[NOTICE] Now listening to 127.0.0.1:53 [TCP]
[NOTICE] […] OK (DNSCrypt) - rtt: 24ms
[NOTICE] […] OK (DNSCrypt) - rtt: 28ms
[NOTICE] Sorted latencies:
[NOTICE] -    24ms …
[NOTICE] -    28ms …
[NOTICE] Server with the lowest initial latency: … (rtt: 24ms)
[NOTICE] dnscrypt-proxy is ready - live servers: 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7577a1]

goroutine 7 [running]:
main.(*BlockedNames).check(0x0, 0xc000056000, 0xc000d2a040, 0x12, 0xb76320, 0x13)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:104 +0x41
main.(*PluginBlockName).Eval(0xc000006068, 0xc000056000, 0xc0000f8090, 0x0, 0x0)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:100 +0xea
main.(*PluginsState).ApplyQueryPlugins(0xc000056000, 0xc0000ec290, 0xc000108000, 0x24, 0xfff, 0xc00015e563, 0x6, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugins.go:251 +0x1fe
main.(*Proxy).processIncomingQuery(0xc0000ec000, 0xc000d280e0, 0x846b67, 0x3, 0x846b67, 0x3, 0xc000108000, 0x24, 0xfff, 0xc000d16000, ...)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/proxy.go:367 +0x274
main.(*Proxy).udpListener.func1(0xc0000ec000, 0xc000108000, 0x24, 0xfff, 0xc000d16000, 0xc000006008)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/proxy.go:219 +0x186
created by main.(*Proxy).udpListener
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/proxy.go:212 +0xc2
```
