### ISSUE TITLE
ver. 2.0.32 crashes on openwrt

### ISSUE THREAD

**Issue by emwe1** [DNSCrypt/dnscrypt-proxy#1052]
2.0.32  crashes on my openwrt (x86-64) system. When starting from cli I get
```
dnscrypt-proxy -config /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x83efaa]

goroutine 22 [running]:
main.(*BlockedNames).check(0x0, 0xc000085ee0, 0xc0000a0370, 0xe, 0xd61920, 0xf)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:104 +0x3a
main.(*PluginBlockName).Eval(0xc00000e090, 0xc000085ee0, 0xc0000e01b0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugin_block_name.go:100 +0xe3
main.(*PluginsState).ApplyQueryPlugins(0xc000085ee0, 0xc0000fe290, 0xc000200000, 0x2b, 0xfff, 0x95b363, 0x1, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/plugins.go:251 +0x1f7
main.(*Proxy).processIncomingQuery(0xc0000fe000, 0x0, 0x95b6dd, 0x3, 0x95b6dd, 0x3, 0xc000200000, 0x2b, 0xfff, 0xc000081160, ...)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/proxy.go:367 +0x26d
main.(*Proxy).udpListener.func1(0xc0000fe000, 0xc000200000, 0x2b, 0xfff, 0xc000081160, 0xc00000e0b0)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/proxy.go:219 +0x17f
created by main.(*Proxy).udpListener
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/proxy.go:212 +0xbb
```
When reinstalling the previous version 2.0.31 it works again.

**Comment by jedisct1** [comment]
Duplicate #1053
