### ISSUE TITLE
Local DoH does not work with 2.0.38

### ISSUE THREAD

**Issue by brandsimon** [DNSCrypt/dnscrypt-proxy#1173]
##  *Who* is the bug affecting?
DoH user

## *What* is affected by this bug?
na

## *When* does this occur?
Every singe DoH request

## *Where* does it happen?
Arch Linux, 64bit

## *How* do we replicate the issue?
make DoH request

## Expected behavior (i.e. solution)
No exception, but DNS response

## Other Comments
Since 2.0.38-1, every DoH request generates the following exception, worked fine with  2.0.36-1
```
 goroutine 59 [running]:
 net/http.(*conn).serve.func1(0xc0000b0aa0)
         /usr/lib/go/src/net/http/server.go:1767 +0x13b 
 panic(0x564776d23a60, 0x564776dbe780)
         /usr/lib/go/src/runtime/panic.go:679 +0x1b6    
 main.addEDNS0PaddingIfNoneFound(0xc0004a7b80, 0xc000285440, 0xe5, 0x21e, 0xffffffffffffffe5, 0x0, 0xc00033c800, 0x34, 0x200,          0xc0004594a0)
         /build/dnscrypt-proxy/src/dnscrypt-proxy-2.0.38/dnscrypt-proxy/dnsutils.go:227 +0x94
 main.localDoHHandler.ServeHTTP(0xc000104000, 0x564776dcfe60, 0xc000268700, 0xc0002e2000)
         /build/dnscrypt-proxy/src/dnscrypt-proxy-2.0.38/dnscrypt-proxy/local-doh.go:63 +0x7bc
 net/http.serverHandler.ServeHTTP(0xc000268000, 0x564776dcfe60, 0xc000268700, 0xc0002e2000)
         /usr/lib/go/src/net/http/server.go:2802 +0xa6  
 net/http.(*conn).serve(0xc0000b0aa0, 0x564776dd0c20, 0xc00037e000)
         /usr/lib/go/src/net/http/server.go:1890 +0x877
 created by net/http.(*Server).Serve
         /usr/lib/go/src/net/http/server.go:2928 +0x386 

```

I am happy to provide more data, if needed.

**Comment by brandsimon** [comment]
This works! Thank you very much for the fast fix!
