### ISSUE TITLE
dnscrypt-proxy doesn't work on DSL-N14U (MIPS) big-endian CPU

### ISSUE THREAD

**Issue by executabls** [DNSCrypt/dnscrypt-proxy#1247]
## That's my device
```
Linux DSL-N14U 2.6.22.15 #1 SMP Sat Nov 30 02:26:27 CST 2019 mips unknown
```
```
CPU Architecture | MIPS 34K (Big Endian) (mips32_r2) (mipsbig) (mips)
```
## What's the trouble?

I get this error when I try to run the application.

```
# cd linux-mips
# ./dnscrypt-proxy
runtime: epollctl failed with 9
fatal error: runtime: epollctl failed

goroutine 1 [running]:
runtime.throw(0x5ac0d6, 0x18)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:1114 +0x60 fp=0xc68d54 sp=0xc68d40 pc=0x4cfa0
runtime.netpollinit()
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/netpoll_epoll.go:49 +0x19c fp=0xc68d8c sp=0xc68d54 pc=0x48bc4
runtime.netpollGenericInit()
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/netpoll.go:112 +0xa0 fp=0xc68d94 sp=0xc68d8c pc=0x46f88
runtime.doaddtimer(0xc20000, 0xc3e304)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/time.go:271 +0x1e8 fp=0xc68dc0 sp=0xc68d94 pc=0x76014
runtime.addInitializedTimer(0xc3e304)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/time.go:258 +0x8c fp=0xc68ddc sp=0xc68dc0 pc=0x75df4
runtime.addtimer(0xc3e304)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/time.go:248 +0x88 fp=0xc68de8 sp=0xc68ddc pc=0x75d38
time.startTimer(0xc3e304)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/time.go:207 +0x3c fp=0xc68df0 sp=0xc68de8 pc=0x75b38
time.AfterFunc(0xd, 0xf8475800, 0x5c6dd4, 0x81a4c602)
        /usr/local/Cellar/go/1.14.1/libexec/src/time/sleep.go:163 +0xc0 fp=0xc68e10 sp=0xc68df0 pc=0xecdb4
crypto/rand.(*devReader).Read(0xc523e0, 0xc18538, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14.1/libexec/src/crypto/rand/rand_unix.go:54 +0x5a4 fp=0xc68e90 sp=0xc68e10 pc=0x2070c4
io.ReadAtLeast(0x662e80, 0xc523e0, 0xc18538, 0x8, 0x8, 0x8, 0x52d880, 0x152c900, 0xc18538)
        /usr/local/Cellar/go/1.14.1/libexec/src/io/io.go:310 +0x98 fp=0xc68ebc sp=0xc68e90 pc=0x95f60
io.ReadFull(...)
        /usr/local/Cellar/go/1.14.1/libexec/src/io/io.go:329
crypto/rand.Read(0xc18538, 0x8, 0x8, 0xc18538, 0x6, 0x0)
        /usr/local/Cellar/go/1.14.1/libexec/src/crypto/rand/rand.go:24 +0x68 fp=0xc68ee4 sp=0xc68ebc pc=0x20682c
main.main()
        /tmp/dnscrypt-proxy/dnscrypt-proxy/main.go:33 +0xa8 fp=0xc68fc0 sp=0xc68ee4 pc=0x4b9b94
runtime.main()
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/proc.go:203 +0x284 fp=0xc68fec sp=0xc68fc0 pc=0x50838
runtime.goexit()
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/asm_mipsx.s:651 +0x4 fp=0xc68fec sp=0xc68fec pc=0x88750
```

## Detailed device specs

[https://github.com/executabls/dsl-n14u_gpl/wiki/Detailed-Device-Specs](https://github.com/executabls/dsl-n14u_gpl/wiki/Detailed-Device-Specs)

**Comment by jedisct1** [comment]
Are you using a precompiled binary or did you compile it yourself?

Did version 1.0.39 exhibit the same behavior?

**Comment by executabls** [comment]
> Are you using a precompiled binary or did you compile it yourself?
> 
> Did version 1.0.39 exhibit the same behavior?

I'm using the precompiled binary.  I think you mean 2.0.39 and i have the similar problem in those versions.

```
# wget https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.0.39/dnscrypt-proxy-linux_mips-2.0.39.tar.gz
Connecting to github.com (140.82.118.3:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.207.123:443)
dnscrypt-proxy-linux 100% |*******************************************************************************|  3489k  0:00:00 ETA
# tar xzf *

#
# cd li*
# ./dns*
runtime: epollwait on fd 89 failed with 9
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x5cac07, 0x17)
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/runtime/panic.go:774 +0x60
runtime.netpoll(0x97ed28, 0x9933)
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/runtime/netpoll_epoll.go:75 +0x2ac
runtime.sysmon()
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/runtime/proc.go:4337 +0x3ac
runtime.mstart1()
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/runtime/proc.go:1201 +0xf0
runtime.mstart()
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/runtime/proc.go:1167 +0x68

goroutine 1 [runnable]:
os/signal.signal_enable(0xf)
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/runtime/sigqueue.go:219 +0xbc
os/signal.enableSignal(...)
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/os/signal/signal_unix.go:50
os/signal.Notify.func1(0xf)
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/os/signal/signal.go:135 +0x108
os/signal.Notify(0xc40300, 0xc6ceac, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/os/signal/signal.go:147 +0x1b8
github.com/kardianos/service.(*sysv).Run.func1()
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/vendor/github.com/kardianos/service/service_sysv_linux.go:146 +0xb0
github.com/kardianos/service.(*sysv).Run(0xc552e0, 0x5c5a72, 0xf)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/vendor/github.com/kardianos/service/service_sysv_linux.go:148 +0xe4
main.main()
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/main.go:105 +0xe2c

goroutine 6 [runnable]:
os/signal.loop()
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/os/signal/signal_unix.go:21
created by os/signal.init.0
        /home/travis/.gimme/versions/go1.13.7.linux.amd64/src/os/signal/signal_unix.go:29 +0x50

goroutine 8 [runnable]:
main.(*App).Start.func1(0xc552c0)
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/main.go:115
created by main.(*App).Start
        /home/travis/gopath/src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/main.go:115 +0x5c
```

**Comment by jedisct1** [comment]
Ah, good news, this is not a regression, then :)

Applications written in Go [require kernel version 2.6.23 or later](https://github.com/golang/go/wiki/MinimumRequirements).

Kernel 2.6.22 was released in year 2007, so not supporting it in 2020 is quite reasonable :)

You have to upgrade your system, sorry.

**Comment by rampageX** [comment]
@executabls Try this firmware see help or not:

https://github.com/gnuton/asus-mediatek-fw/tree/dsl-n14u
