### ISSUE TITLE
panic sometime 

### ISSUE THREAD

**Issue by falconray0704** [DNSCrypt/dnscrypt-proxy#189]
**running config:**
1) use public-resolvers
2) server_names = ['yandex', 'doh-crypto-sx'] 

**panic info** 

```
ray@ubuntu:~/dnsCryptProxy$ sudo ./dnscrypt-proxy start
[2018-02-26 05:26:03] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
[2018-02-26 05:26:03] [NOTICE] dnscrypt-proxy 2.0.4
[2018-02-26 05:26:03] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
[2018-02-26 05:26:03] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
[2018-02-26 05:26:03] [NOTICE] Now listening to [::1]:53 [UDP]
[2018-02-26 05:26:03] [NOTICE] Now listening to [::1]:53 [TCP]
panic: interface conversion: dns.RR is *dns.OPT, not *dns.A

goroutine 6 [running]:
main.(*XTransport).Fetch(0xc420074370, 0x88038e, 0x4, 0xc420178280, 0x88a0e0, 0x1d, 0x88a0e0, 0x1d, 0xc4200469d0, 0xb2d05e00, ...)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/xtransport.go:148 +0x14a1
main.(*XTransport).Post(0xc420074370, 0xc420178280, 0x88a0e0, 0x1d, 0x88a0e0, 0x1d, 0xc420168100, 0x1c, 0x1c, 0xb2d05e00, ...)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/xtransport.go:178 +0x15a
main.(*XTransport).DoHQuery(0xc420074370, 0xc420168100, 0xc420178280, 0xc420168100, 0x1c, 0x1c, 0xb2d05e00, 0x0, 0x0, 0x0, ...)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/xtransport.go:192 +0x6b3
main.(*ServersInfo).fetchDoHServerInfo(0xc42008acf0, 0xc42008ac80, 0xc420115a26, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200dee80, ...)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:271 +0x17f
main.(*ServersInfo).fetchServerInfo(0xc42008acf0, 0xc42008ac80, 0xc420115a26, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200dee80, ...)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:213 +0x1a6
main.(*ServersInfo).refreshServer(0xc42008acf0, 0xc42008ac80, 0xc420115a26, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200dee80, ...)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:104 +0x22e
main.(*ServersInfo).refresh(0xc42008acf0, 0xc42008ac80, 0x0, 0x0, 0xc4201740f0)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:129 +0x19c
main.(*Proxy).StartProxy(0xc42008ac80)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/proxy.go:85 +0x3f8
main.(*App).AppMain(0xc4200a2840, 0xc42008ac80)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/main.go:96 +0x2b
main.(*App).Start.func1(0xc4200a2840, 0xc42008ac80)
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/main.go:87 +0x35
created by main.(*App).Start
	/opt/github/dnscrypt-proxy/dnscrypt-proxy/main.go:86 +0x143
ray@ubuntu:~/dnsCryptProxy$ 
```

**Comment by jedisct1** [comment]
Ah, my bad :(

This has been fixed. Thanks again for reporting this!
