### ISSUE TITLE
fatal error: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by vladns** [DNSCrypt/dnscrypt-proxy#201]
Approximately once a day there is an error:
```
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: fatal error: sync: unlock of unlocked mutex
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: goroutine 2856 [running]:
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: runtime.throw(0x869382, 0x1e)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:619 +0x81 fp=0xc420295c30 sp=0xc420295c10 pc=0x42b2e1
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: sync.throw(0x869382, 0x1e)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:608 +0x35 fp=0xc420295c50 sp=0xc420295c30 pc=0x42b255
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: sync.(*Mutex).Unlock(0xc420390000)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/.gimme/versions/go1.10.linux.amd64/src/sync/mutex.go:184 +0xc2 fp=0xc420295c78 sp=0xc420295c50 pc=0x4600b2
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: sync.(*RWMutex).Unlock(0xc420390000)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/.gimme/versions/go1.10.linux.amd64/src/sync/rwmutex.go:132 +0x7e fp=0xc420295ca8 sp=0xc420295c78 pc=0x460dde
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: main.(*ServerInfo).noticeBegin(0xc420390000, 0xc4200e8c80)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:347 +0x74 fp=0xc420295cd0 sp=0xc420295ca8 pc=0x782bf4
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: main.(*Proxy).processIncomingQuery(0xc4200e8c80, 0xc420390000, 0x85e4fe, 0x3, 0x85e4fe, 0x3, 0xc4204fb000, 0x1f, 0xfff, 0xc4203e84b0, ...)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:275 +0xb29 fp=0xc420295f30 sp=0xc420295cd0 pc=0x77eae9
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: main.(*Proxy).udpListener.func1(0xc4200e8c80, 0xc4204fb000, 0x1f, 0xfff, 0xc4203e84b0, 0xc4200b4090)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:141 +0x10e fp=0xc420295fb0 sp=0xc420295f30 pc=0x78b9ee
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: runtime.goexit()
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420295fb8 sp=0xc420295fb0 pc=0x457c91
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: created by main.(*Proxy).udpListener
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:135 +0x9a
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: goroutine 1 [chan receive, 70 minutes]:
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service.(*systemd).Run.func1()
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service/service_systemd_linux.go:138 +0xbd
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service.(*systemd).Run(0xc42013c2c0, 0x11, 0xc4201a3cf0)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service/service_systemd_linux.go:139 +0xc0
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: main.main()
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/main.go:67 +0x588
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: goroutine 35 [syscall, 70 minutes]:
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: os/signal.signal_recv(0x0)
...
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: main.(*Proxy).processIncomingQuery(0xc4200e8c80, 0xc420390000, 0x85e4fe, 0x3, 0x85e4fe, 0x3, 0xc4202b2000, 0x1f, 0xfff, 0xc4203d41d0, ...)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:277 +0xc84
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: main.(*Proxy).udpListener.func1(0xc4200e8c80, 0xc4202b2000, 0x1f, 0xfff, 0xc4203d41d0, 0xc4200b4090)
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:141 +0x10e
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: created by main.(*Proxy).udpListener
Mar  1 11:31:11 home-router dnscrypt-proxy[8167]: #011/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:135 +0x9a
Mar  1 11:31:11 home-router systemd[1]: dnscrypt-proxy.service: Service hold-off time over, scheduling restart.
Mar  1 11:31:11 home-router systemd[1]: Stopped DNSCrypt client proxy.
Mar  1 11:31:11 home-router systemd[1]: Started DNSCrypt client proxy.
```
I added "Restart=always" to the section "[Service]" as a workaround.
dnscrypt-proxy 2.0.5

**Comment by jedisct1** [comment]
Yes, I saw that as well. I don't know how to fix it. Can you help?
