### ISSUE TITLE
dnscrypt-proxy on Openwrt crashes

### ISSUE THREAD

**Issue by githubcdr** [DNSCrypt/dnscrypt-proxy#230]
Hi,

For some reason dnscrypt-proxy seems to stop and die once in a while, running on OpenWRT Linux  4.9.82 #0 SMP Sat Feb 24 15:12:57 2018 armv7l GNU/Linux

I noticed this in the logs

```
panic: runtime error: slice bounds out of range

goroutine 3244 [running]:
main.ReadPrefixed(0x13defb98, 0xe195aae5, 0xbea2fbcb, 0xa321dd88, 0xab, 0x5e93a8)
        /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/common.go:67 +0x294
main.(*Proxy).tcpListener.func1(0x427d18, 0x13defb98, 0x119c01a0)
        /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:174 +0xf8
created by main.(*Proxy).tcpListener
        /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:166 +0x78

```

Is this a bug or a memory issue?

**Comment by jedisct1** [comment]
This is a bug that I think was fixed in ba2f43e6db22b35dd66061cc30dce591259db576
