### ISSUE TITLE
Errors encountered running generate-domains-blocklist.py on Fedora 38

### ISSUE THREAD

**Issue by solidc0re** [DNSCrypt/dnscrypt-proxy#2477]
Context: Installed dnscrypt-proxy 2.1.5 on Fedora 38 using the instructions from the Wiki. All works fine and as expected.

I am working on combining blocklists and am running into various errors with the generate-domain-blocklist.py script.

- dnscrypt-proxy is saved in /opt/dnscrypt-proxy
- generate-domains-blocklist.py is also saved in /opt/dnscrypt-proxy

1. It doesn't recognise the domains-blocklist.conf in the very same folder it is in (/opt/dnscrypt-proxy). As follows:

```
$ sudo python3 /opt/dnscrypt-proxy/generate-domains-blocklist.py -i -o blocklist.txt
Traceback (most recent call last):
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 349, in <module>
    blocklists_from_config_file(
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 199, in blocklists_from_config_file
    with open(file) as fd:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'domains-blocklist.conf'
```

2. I therefore specify the exact location using the -c flag, which generates another error about domains-time-restricted.txt. As follows:

```
$ sudo python3 /opt/dnscrypt-proxy/generate-domains-blocklist.py -c /opt/dnscrypt-proxy/domains-blocklist.conf -i -o blocklist.txt
Loading data from [https://adaway.org/hosts.txt]
...
Loading data from [file:domains-time-restricted.txt]
Traceback (most recent call last):
  File "/usr/lib64/python3.11/urllib/request.py", line 1505, in open_local_file
    stats = os.stat(localfile)
            ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'domains-time-restricted.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 121, in load_from_url
    response = urllib.urlopen(req, timeout=int(args.timeout))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 1483, in file_open
    return self.open_local_file(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 1522, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'domains-time-restricted.txt'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 349, in <module>
    blocklists_from_config_file(
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 225, in blocklists_from_config_file
    time_restricted_content, _trusted = load_from_url(time_restricted_url)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 123, in load_from_url
    raise Exception("[{}] could not be loaded: {}\n".format(url, err))
Exception: [file:domains-time-restricted.txt] could not be loaded: <urlopen error [Errno 2] No such file or directory: 'domains-time-restricted.txt'>

```

3. I therefore downloaded the example domains-time-restricted.txt and used the -r flag to specify its location...

```
$ sudo python3 /opt/dnscrypt-proxy/generate-domains-blocklist.py -c /opt/dnscrypt-proxy/domains-blocklist.conf -r /opt/dnscrypt-proxy/domains-time-restricted.txt -i -o blocklist.txt
[sudo] password for test: 
Loading data from [https://adaway.org/hosts.txt]
...
Loading data from [file:domains-allowlist.txt]
Traceback (most recent call last):
  File "/usr/lib64/python3.11/urllib/request.py", line 1505, in open_local_file
    stats = os.stat(localfile)
            ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'domains-allowlist.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 121, in load_from_url
    response = urllib.urlopen(req, timeout=int(args.timeout))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 1483, in file_open
    return self.open_local_file(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 1522, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'domains-allowlist.txt'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 349, in <module>
    blocklists_from_config_file(
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 244, in blocklists_from_config_file
    allowed_names |= allowlist_from_url(allowlist)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 183, in allowlist_from_url
    content, trusted = load_from_url(url)
                       ^^^^^^^^^^^^^^^^^^
  File "/opt/dnscrypt-proxy/generate-domains-blocklist.py", line 123, in load_from_url
    raise Exception("[{}] could not be loaded: {}\n".format(url, err))
Exception: [file:domains-allowlist.txt] could not be loaded: <urlopen error [Errno 2] No such file or directory: 'domains-allowlist.txt'>
```

At this point I get fed up and just wish it would work as per the instructions.

## *What* is affected by this bug?

Ability to generate dnscrypt-proxy blocklist file.

## *When* does this occur?

See above.

## *Where* does it happen?

See above.

## *How* do we replicate the issue?

See above.

## Expected behavior (i.e. solution)

That generate-domains-blocklist.py runs as per the instructions given in the Wiki:

`$ python3 /opt/dnscrypt-proxy/generate-domains-blocklist.py -i -o blocklist.txt`

**Comment by lifenjoiner** [comment]
Run it from the directory where the script locates, or you should provide all necessary files with full path.

**Comment by jedisct1** [comment]
As @lifenjoiner  said, unless a path is specified, files are relative to the current directory.

So, yes, go inside the directory where the files are (with the `cd` command) before running the script.

Or if you really to want to provide absolute paths, use the `-a`, `-c`, `-r` options (type `generate-domains-blocklist.py -h` or `--help` to print the list of commands).
