### ISSUE TITLE
random_padding crash

### ISSUE THREAD

**Issue by char101** [DNSCrypt/dnscrypt-proxy#446]
Hi,

Experienced this crash with dnscrypt-proxy 2.0.11 & 2.0.12:

```
dnscrypt-proxy[25935]: panic: runtime error: invalid memory address or nil pointer dereference
dnscrypt-proxy[25935]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7e928e]
dnscrypt-proxy[25935]: goroutine 6293 [running]:
dnscrypt-proxy[25935]: main.(*XTransport).DoHQuery(0xc42016e2a0, 0xc42016c001, 0xc420b88d80, 0xc4200980f0, 0x40, 0x42, 0x9502f900, 0x42, 0x0, 0x0, ...)
dnscrypt-proxy[25935]: /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/xtransport.go:267 +0x3ce
dnscrypt-proxy[25935]: main.(*Proxy).processIncomingQuery(0xc42016c018, 0xc42052a9a0, 0x8d4dc7, 0x3, 0x8d4dc7, 0x3, 0xc420dfd000, 0x35, 0xfff, 0xc420182dc0, ...)
dnscrypt-proxy[25935]: /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:297 +0x30b
dnscrypt-proxy[25935]: main.(*Proxy).udpListener.func1(0xc42016c018, 0xc420dfd000, 0x35, 0xfff, 0xc420182dc0, 0xc4200a00a0)
dnscrypt-proxy[25935]: /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:149 +0x10e
dnscrypt-proxy[25935]: created by main.(*Proxy).udpListener
dnscrypt-proxy[25935]: /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:143 +0x9a
systemd[1]: dnscrypt-proxy.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

I think this is caused when `makePad` returns a `nil` value.

**Comment by jedisct1** [comment]
Thank you!
