### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by siavashs** [DNSCrypt/dnscrypt-proxy#464]
I'm running `dnscrypt-proxy` on Linux ARM and faced this issue.
While it happened only once so far, it seems like a bug:
```
May 23 05:21:21 cubox dnscrypt-proxy[686]: panic: runtime error: invalid memory address or nil pointer dereference
May 23 05:21:21 cubox dnscrypt-proxy[686]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x377ab8]
May 23 05:21:21 cubox dnscrypt-proxy[686]: goroutine 19985 [running]:
May 23 05:21:21 cubox dnscrypt-proxy[686]: main.(*XTransport).DoHQuery(0x118a2230, 0x11916001, 0x119ff080, 0x1187e050, 0x40, 0x42, 0x9502f900, 0x0, 0x0, 0x0, ...)
May 23 05:21:21 cubox dnscrypt-proxy[686]:         /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/xtransport.go:267 +0x2cc
May 23 05:21:21 cubox dnscrypt-proxy[686]: main.(*Proxy).processIncomingQuery(0x11916014, 0x1199b970, 0x41fd45, 0x3, 0x41fd45, 0x3, 0x11d69000, 0x40, 0xfff, 0x11948000, ...)
May 23 05:21:21 cubox dnscrypt-proxy[686]:         /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:297 +0x204
May 23 05:21:21 cubox dnscrypt-proxy[686]: main.(*Proxy).udpListener.func1(0x11916014, 0x11d69000, 0x40, 0xfff, 0x11948000, 0x1192c640)
May 23 05:21:21 cubox dnscrypt-proxy[686]:         /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:149 +0xbc
May 23 05:21:21 cubox dnscrypt-proxy[686]: created by main.(*Proxy).udpListener
May 23 05:21:21 cubox dnscrypt-proxy[686]:         /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:143 +0x74
```
Let me know if you need more information.

**Comment by jedisct1** [comment]
Bet you are running an old version. Update to the current stable one (2.0.14 at this time).

**Comment by siavashs** [comment]
I'm running **2.0.12**, not too old. I don't see a related bugfix in your new versions.
Anyway I'll update to the latest version and let you know if it happens again.
