### ISSUE TITLE
panic: runtime error: index out of range (linux/arm, versions after 2.0.19, due to cloaking?)

### ISSUE THREAD

**Issue by InkblotAdmirer** [DNSCrypt/dnscrypt-proxy#807]
dnscrypt-proxy is crashing every few hours when using cloaking -- the last version that did not crash when using the cloaking plugin is 2.0.19.  I have yet to see crash when cloaking isn't enabled.

Binary version: dnscrypt-proxy-linux_arm-2.0.21/22/23

Log content follows:
~~~~
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]: panic: runtime error: index out of range
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]:
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]: goroutine 14596 [running]:
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]: main.(*PluginCloak).Eval(0x20dac40, 0x2278c40, 0x22e76d0, 0x0, 0x0)
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]:      /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/plugin_cloak.go:161 +0xc44
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]: main.(*PluginsState).ApplyQueryPlugins(0x2278c40, 0x20b8190, 0x2132000, 0x25, 0xfff, 0x5bf30282, 0x80000000, 0x0, 0xb7e60504, 0x0)
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]:      /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/plugins.go:176 +0x124
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]: main.(*Proxy).processIncomingQuery(0x20b8010, 0x20a66e0, 0x496703, 0x3, 0x496703, 0x3, 0x2132000, 0x25, 0xfff, 0x22b4258, ...)
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]:      /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:333 +0x10c
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]: main.(*Proxy).udpListener.func1(0x20b8010, 0x2132000, 0x25, 0xfff, 0x22b4258, 0x217c010)
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]:      /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:214 +0xbc
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]: created by main.(*Proxy).udpListener
Tue Apr 30 14:51:24 2019 daemon.err dnscrypt-proxy[18594]:      /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:208 +0x74
~~~~

**Comment by jedisct1** [comment]
Hi, and thanks for your report.

If you know how to build the code from source, can you try the current code in git?

50a2018 may fix your issue.

**Comment by InkblotAdmirer** [comment]
I have been using the binary and at some point will get around to creating a toolchain set up to cross compile.  In the likely event that doesn't happen before the next release, I'll just report back then.

Many thanks for creating and maintaining this project!

**Comment by jedisct1** [comment]
Cross-compilation in Go is very easy, because the standard binary can already cross-compile to everything!
